services:
  gmail-agent:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"   
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - gmail-agent-network

networks:
  gmail-agent-network:
    driver: bridge