from uagents import Agent, Context
from models import PromptRequest, PromptResponse

# Address of the Gemini agent we want to communicate with.
# In a real scenario, this would be the actual address printed by the gemini_agent on startup.
# Since we are running locally with a known seed, we can pre-calculate it or configure it.
# For this example, we'll assume the user agent knows the gemini agent's address.
# The address below is derived from the seed "gemini_agent_recovery_seed".
GEMINI_AGENT_ADDRESS = "agent1qdzh0lq802u3a8z7w9j83vntx23x7hmsuudflh2pwy005y5a5y4yv5f3rd6"

# Create the user agent
agent = Agent(
    name="user_agent",
    seed="user_agent_recovery_seed",
    port=8002,
    endpoint=["http://127.0.0.1:8002/submit"],
)

# Example prompt to send
PROMPT_TEXT = "Explain the concept of decentralized AI agents in two short sentences."

@agent.on_event("startup")
async def startup(ctx: Context):
    """
    Startup event handler.
    The agent will send a PromptRequest to the Gemini agent when it starts.
    """
    ctx.logger.info(f"Starting User Agent: {agent.name}")
    ctx.logger.info(f"Agent address: {agent.address}")
    
    ctx.logger.info(f"Sending prompt to Gemini Agent at {GEMINI_AGENT_ADDRESS}...")
    
    # Send the PromptRequest message
    await ctx.send(
        GEMINI_AGENT_ADDRESS, 
        PromptRequest(prompt=PROMPT_TEXT)
    )

@agent.on_message(model=PromptResponse)
async def handle_prompt_response(ctx: Context, sender: str, msg: PromptResponse):
    """
    Message handler for receiving PromptResponse messages.
    Logs the response generated by the AI or any errors.
    """
    ctx.logger.info(f"Received response from {sender}:")
    
    if msg.error:
        ctx.logger.error(f"Error from Gemini Agent: {msg.error}")
    else:
        ctx.logger.info(f"AI Response: \n{msg.response}")

if __name__ == "__main__":
    agent.run()
